-- Versiona a estrutura de campanhas que havia sido criada manualmente e
-- adiciona rastreamento idempotente por cliente.
CREATE TABLE IF NOT EXISTS public.campanhas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  texto TEXT NOT NULL DEFAULT '',
  midia_tipo TEXT,
  midia_url TEXT,
  midia_nome TEXT,
  status TEXT NOT NULL DEFAULT 'rascunho',
  total_clientes INTEGER NOT NULL DEFAULT 0,
  enviadas INTEGER NOT NULL DEFAULT 0,
  erros INTEGER NOT NULL DEFAULT 0,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  enviado_em TIMESTAMPTZ
);

ALTER TABLE public.campanhas
  ADD COLUMN IF NOT EXISTS texto TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS midia_tipo TEXT,
  ADD COLUMN IF NOT EXISTS midia_url TEXT,
  ADD COLUMN IF NOT EXISTS midia_nome TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'rascunho',
  ADD COLUMN IF NOT EXISTS total_clientes INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS enviadas INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS erros INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS enviado_em TIMESTAMPTZ;

UPDATE public.campanhas
SET status = 'rascunho'
WHERE status NOT IN ('rascunho', 'enviando', 'enviada');

UPDATE public.campanhas
SET midia_tipo = NULL,
    midia_url = NULL,
    midia_nome = NULL
WHERE midia_tipo NOT IN ('imagem', 'video')
   OR (midia_tipo IS NULL AND (midia_url IS NOT NULL OR midia_nome IS NOT NULL));

ALTER TABLE public.campanhas
  DROP CONSTRAINT IF EXISTS campanhas_status_check,
  DROP CONSTRAINT IF EXISTS campanhas_midia_tipo_check,
  DROP CONSTRAINT IF EXISTS campanhas_totais_check;

ALTER TABLE public.campanhas
  ADD CONSTRAINT campanhas_status_check
    CHECK (status IN ('rascunho', 'enviando', 'enviada')),
  ADD CONSTRAINT campanhas_midia_tipo_check
    CHECK (midia_tipo IS NULL OR midia_tipo IN ('imagem', 'video')),
  ADD CONSTRAINT campanhas_totais_check
    CHECK (total_clientes >= 0 AND enviadas >= 0 AND erros >= 0);

CREATE TABLE IF NOT EXISTS public.campanha_envios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campanha_id BIGINT NOT NULL REFERENCES public.campanhas(id) ON DELETE CASCADE,
  cliente_id BIGINT NOT NULL REFERENCES public.clientes(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'processando',
  detalhe TEXT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  enviado_em TIMESTAMPTZ,
  CONSTRAINT campanha_envios_status_check
    CHECK (status IN ('processando', 'enviada', 'erro')),
  CONSTRAINT campanha_envios_campanha_cliente_key
    UNIQUE (campanha_id, cliente_id)
);

CREATE INDEX IF NOT EXISTS campanha_envios_campanha_idx
  ON public.campanha_envios (campanha_id, status);

CREATE OR REPLACE FUNCTION public.campanha_inc_enviadas(p_id BIGINT)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE public.campanhas
  SET enviadas = enviadas + 1
  WHERE id = p_id;
$$;

CREATE OR REPLACE FUNCTION public.campanha_inc_erros(p_id BIGINT)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE public.campanhas
  SET erros = erros + 1
  WHERE id = p_id;
$$;

ALTER TABLE public.campanhas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campanha_envios ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.campanhas FROM anon, authenticated;
REVOKE ALL ON TABLE public.campanha_envios FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.campanha_envios_id_seq FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.campanha_inc_enviadas(BIGINT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.campanha_inc_erros(BIGINT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.campanha_inc_enviadas(BIGINT) TO service_role;
GRANT EXECUTE ON FUNCTION public.campanha_inc_erros(BIGINT) TO service_role;

INSERT INTO storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
VALUES (
  'campanhas',
  'campanhas',
  true,
  16777216,
  ARRAY[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'video/mp4',
    'video/quicktime',
    'video/webm'
  ]
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;
